### ISSUE TITLE
Exception occured

### ISSUE THREAD

**Issue by cliffordsnow** [joshdoe/josm-conflation-plugin#4]
We are attempting to use the conflation plugin to import Seattle addresses. I'm getting an error on both my linux box running josm 5665 with the current plugin and on a mac box running version 5608. The exception occurs when attempting to conflate. 

Below is the exception report
Repository Root: http://josm.openstreetmap.de/svn
Build-Date: 2012-11-29 02:31:07
Last Changed Author: stoecker
Revision: 5608
Repository UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
URL: http://josm.openstreetmap.de/svn/trunk
Last Changed Date: 2012-11-28 23:47:46 +0100 (Wed, 28 Nov 2012)
Last Changed Rev: 5608

Identification: JOSM/1.5 (5608 en)
Memory Usage: 95 MB / 505 MB (30 MB allocated, but free)
Java version: 1.6.0_37, Apple Inc., Java HotSpot(TM) 64-Bit Server VM
Operating system: Mac OS X
Dataset consistency test: No problems found

Plugin: ImportImagePlugin (29028)
Plugin: buildings_tools (28891)
Plugin: conflation (0.1.6)
Plugin: geotools (29116)
Plugin: jts (28945)
Plugin: log4j (28968)
Plugin: mapdust (28807)
Plugin: measurement (28898)
Plugin: openstreetbugs (28807)
Plugin: pdfimport (28807)
Plugin: restart (28492)
Plugin: utilsplugin2 (29124)
Plugin: wikipedia (29068)

java.lang.NullPointerException
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog.getSelectedReferencePrimitives(ConflationToggleDialog.java:211)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog.getAllSelectedPrimitives(ConflationToggleDialog.java:236)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog.access$200(ConflationToggleDialog.java:40)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog$SelectListSelectionAction.updateEnabledState(ConflationToggleDialog.java:682)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog$SelectListSelectionAction.valueChanged(ConflationToggleDialog.java:687)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:167)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:147)
    at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:194)
    at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:388)
    at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:398)
    at javax.swing.DefaultListSelectionModel.removeSelectionIntervalImpl(DefaultListSelectionModel.java:559)
    at javax.swing.DefaultListSelectionModel.clearSelection(DefaultListSelectionModel.java:403)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog.simpleMatchSelectionChanged(ConflationToggleDialog.java:187)
    at org.openstreetmap.josm.plugins.conflation.SimpleMatchList.fireSelectionChanged(SimpleMatchList.java:160)
    at org.openstreetmap.josm.plugins.conflation.SimpleMatchList.removeAll(SimpleMatchList.java:139)
    at org.openstreetmap.josm.plugins.conflation.SimpleMatchList.remove(SimpleMatchList.java:96)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog.primitivesRemoved(ConflationToggleDialog.java:747)
    at org.openstreetmap.josm.data.osm.event.PrimitivesRemovedEvent.fire(PrimitivesRemovedEvent.java:25)
    at org.openstreetmap.josm.data.osm.DataSet.fireEventToListeners(DataSet.java:1018)
    at org.openstreetmap.josm.data.osm.DataSet.endUpdate(DataSet.java:997)
    at org.openstreetmap.josm.data.osm.DataSet.removePrimitive(DataSet.java:411)
    at org.openstreetmap.josm.command.AddPrimitivesCommand.undoCommand(AddPrimitivesCommand.java:93)
    at org.openstreetmap.josm.plugins.conflation.ConflateMatchCommand.<init>(ConflateMatchCommand.java:53)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog$ConflateAction.conflateMatchActionPerformed(ConflationToggleDialog.java:570)
    at org.openstreetmap.josm.plugins.conflation.ConflationToggleDialog$ConflateAction.actionPerformed(ConflationToggleDialog.java:547)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:272)
    at java.awt.Component.processMouseEvent(Component.java:6382)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
    at java.awt.Component.processEvent(Component.java:6147)
    at java.awt.Container.processEvent(Container.java:2083)
    at java.awt.Component.dispatchEventImpl(Component.java:4744)
    at java.awt.Container.dispatchEventImpl(Container.java:2141)
    at java.awt.Component.dispatchEvent(Component.java:4572)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4619)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4280)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4210)
    at java.awt.Container.dispatchEventImpl(Container.java:2127)
    at java.awt.Window.dispatchEventImpl(Window.java:2489)
    at java.awt.Component.dispatchEvent(Component.java:4572)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:704)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:663)
    at java.awt.EventQueue$2.run(EventQueue.java:661)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:677)
    at java.awt.EventQueue$3.run(EventQueue.java:675)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:674)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by joshdoe** [comment]
Could you provide OSM file(s) and relevant selections? If I can recreate it exactly on my machine it's much easier to debug. Thanks for the feedback, and good to know others are interested in this plugin.

**Comment by cliffordsnow** [comment]
Josh,
Thanks for helping out. We are very definitely interested in the plugin.
I've attached a copy of
Wallingford.osm which contains addresses we plan to import. The area it
covers is Wallingford in Seattle, King County, WA.

I've tried it on a linux, ubuntu running version 5665 of JOSM and on my Mac
running version 5608. The error  happens when you click on conflate after
freezing the reference and subject data. Increasing JOSM memory to 1Gb did
not help. I'm only picking a city block at a time, not the entire
neighborhood contained in Wallingford.osm.

Thanks,
Clifford

On Mon, Jan 21, 2013 at 9:46 AM, joshdoe notifications@github.com wrote:

> Could you provide OSM file(s) and relevant selections? If I can recreate
> it exactly on my machine it's much easier to debug. Thanks for the
> feedback, and good to know others are interested in this plugin.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshdoe/josm-conflation-plugin/issues/4#issuecomment-12508971.

## 

Clifford

OpenStreetMap: Maps with a human touch

**Comment by joshdoe** [comment]
Hi Clifford, I don't see an attachment, you'll have to put on something like DropBox or send it to me via email.

**Comment by joshdoe** [comment]
I think I fixed it, at least in part. Does it only happen after conflating the last match? If not, I might need a more detailed reproduction description from you. I'll update the plugin a little later, but sent one off to Clifford.
